namespace TransportLinesManager.Utils
{
    public enum NamingType
    {
        NONE,
        PLANE,
        BLIMP,
        SHIP,
        FERRY,
        TRAIN,
        MONORAIL,
        TRAM,
        METRO,
        BUS,
        TOUR_BUS,
        CABLE_CAR,
        MONUMENT,
        BEAUTIFICATION,
        HEALTHCARE,
        POLICEDEPARTMENT,
        FIREDEPARTMENT,
        EDUCATION,
        DISASTER,
        UTILITY,
        CAMPUS,
        PARKAREA,
        INDUSTRY_AREA,
        DISTRICT,
        ADDRESS,
        RICO,
        TROLLEY,
        HELICOPTER,
        TERMINAL,
        BANK,
        SERVICE_POINT,
        HOTEL,
        RACE
    }

}
